### ISSUE TITLE
Start debugging in VSCode 1.56.0

### ISSUE THREAD

**Issue by carlosmgilp** [Autodesk-AutoCAD/AutoLispExt#143]
**Describe the bug**
When trying to debug my code, it shows me a warning.

![image](https://user-images.githubusercontent.com/80189444/117556013-77d17080-b032-11eb-893f-fd849797ff3f.png)

And I am clear that the extension is installed.

![image](https://user-images.githubusercontent.com/80189444/117556038-c7b03780-b032-11eb-961b-86a02dc6826a.png)

If I install an older version of VSCode, it works fine.

**Desktop**
 - Windows 10
 - VSCode 1.56.0
 - Autocad 2022
 - AutoCAD AutoLISP Extension 1.4.0

**Comment by nigma456** [comment]
Thanks for reporting this issue to us! We will look into it.

**Comment by enevre** [comment]
I also have same problem.

**Comment by Sen-real** [comment]
@carlosmgilp @enevre 
It's a result of the recent VS Code upgrade. Other extensions get into the same problem too. 
Please check if it can be solved with following steps:
1. Close current folder, and open a LSP file (so that we can generate a global configuration for LSP)
![image](https://user-images.githubusercontent.com/57521938/118247268-92de2d80-b4d5-11eb-9d34-357eefe51f8e.png)
2. Click here to add configuration
![image](https://user-images.githubusercontent.com/57521938/118246435-886f6400-b4d4-11eb-9f22-f2476e6f5dfc.png)
3. In the editor of "settings.json", select the following item to add an configuration for Attach mode:
![image](https://user-images.githubusercontent.com/57521938/118248674-2cf2a580-b4d7-11eb-9991-991ebc1431b6.png)
4. Save the automatically generated configuration file (settings.json):
![image](https://user-images.githubusercontent.com/57521938/118249126-a5596680-b4d7-11eb-86da-68aa6d1e69e1.png)
It should be good enough for Attach mode.

**Comment by Sen-real** [comment]
CONTINUED:
If we want to not only Attach but also Launch:
5. repeat step 3, select "AutoLISP Debug: **Launch**", and save the automatically updated settings.json
6. open VS Code setting page from here:
![image](https://user-images.githubusercontent.com/57521938/118251152-ca4ed900-b4d9-11eb-8665-9835772ded70.png)
7. type "autolispext" in the filter box, and input the path of acad.exe on the machine:
![image](https://user-images.githubusercontent.com/57521938/118251317-02eeb280-b4da-11eb-9e2a-f1edf7c96ed9.png)
8. as now both Attach and Launch are configured, we need to select the active/current debug mode
![image](https://user-images.githubusercontent.com/57521938/118251411-244f9e80-b4da-11eb-91f6-c3f1a8c73c28.png)

**Comment by LanDong-adsk** [comment]
Meanwhile, we are preparing for an official release to address this issue.

**Comment by dmcdonoughwick** [comment]
I've gotten this to work by ensuring I have the process name filled out under "Workspace" as well as "User" under the extension settings.

**Comment by Sen-real** [comment]
Solved, please update AutolispExt to 1.5.0, and update VS Code to the latest version.
