### ISSUE TITLE
Not recognized as a debugger 

### ISSUE THREAD

**Issue by krebskyl** [Autodesk-AutoCAD/AutoLispExt#147]
Issue Type: <b>Bug</b>

When starting to run the debugger, the AutoLISP extension is no longer recognized as a debugger and VS Code prompts me to search for @category:debuggers in the Extension Marketplace.

Extension version: 1.4.0
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.44GB free)|
|Process Argv|--crash-reporter-id 3d6ee9c7-572a-4315-b48d-5450da59492f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30299255

```

</details>

**Comment by Sen-real** [comment]
@krebskyl 
It's a result of the recent VS Code upgrade. Other extensions get into the same problem too. 
Please check if it can be solved with following steps:
1. Close current folder, and open a LSP file (so that we can generate a global configuration for LSP)
![image](https://user-images.githubusercontent.com/57521938/118247268-92de2d80-b4d5-11eb-9d34-357eefe51f8e.png)
2. Click here to add configuration
![image](https://user-images.githubusercontent.com/57521938/118246435-886f6400-b4d4-11eb-9f22-f2476e6f5dfc.png)
3. In the editor of "settings.json", select the following item to add an configuration for Attach mode.
Then the automatically generated configuration should be good enough for Attach mode.

**Comment by Sen-real** [comment]
closed as it's a duplication of[ issue 143](https://github.com/Autodesk-AutoCAD/AutoLispExt/issues/143)

**Comment by Sen-real** [comment]
Solved, please:
- update AutolispExt(AutoCAD AutoLISP extension) to 1.5.0, and
- update VS Code to the latest version.
